### ISSUE TITLE
invalid token error

### ISSUE THREAD

**Issue by mikefarace** [Bigouden/VMKey#1]
Hi,

I installed Pything 3.6 and pip on Windows server 2012, and installed prerequisites.  Any idea why I am getting this error?

----------------------------------------

C:\Users\Administrator>VMKey.py --help
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\VMKey.py", line 97
    return (int(hid, 16) << 16 | 0007)
                                    ^
SyntaxError: invalid token

**Comment by Bigouden** [comment]
Could you please try it with Python 2.X banch ?

**Comment by Bigouden** [comment]
Hi,

Could you try it and give me a feedback ?

https://github.com/Bigouden/VMKey/blob/devel/vm_key.py

++

Thomas

**Comment by Bigouden** [comment]
Fix in latest release
